# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dwgFile_pb2 as dwgFile__pb2


class CADParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.parseCADFile = channel.unary_unary(
                '/CADParser.CADParser/parseCADFile',
                request_serializer=dwgFile__pb2.parseCADRequest.SerializeToString,
                response_deserializer=dwgFile__pb2.parseCADResult.FromString,
                )


class CADParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def parseCADFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CADParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'parseCADFile': grpc.unary_unary_rpc_method_handler(
                    servicer.parseCADFile,
                    request_deserializer=dwgFile__pb2.parseCADRequest.FromString,
                    response_serializer=dwgFile__pb2.parseCADResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CADParser.CADParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CADParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def parseCADFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CADParser.CADParser/parseCADFile',
            dwgFile__pb2.parseCADRequest.SerializeToString,
            dwgFile__pb2.parseCADResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
