# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dwgFile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdwgFile.proto\x12\tCADParser\"W\n\x0fparseCADRequest\x12%\n\x08metadata\x18\x01 \x01(\x0b\x32\x13.CADParser.MetaData\x12\x1d\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x0f.CADParser.File\"V\n\x0eparseCADResult\x12%\n\x08metadata\x18\x01 \x01(\x0b\x32\x13.CADParser.MetaData\x12\x1d\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x0f.CADParser.File\"&\n\x08MetaData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"\x17\n\x04\x46ile\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c*?\n\x06Status\x12\x0b\n\x07PENDING\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x32T\n\tCADParser\x12G\n\x0cparseCADFile\x12\x1a.CADParser.parseCADRequest\x1a\x19.CADParser.parseCADResult\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dwgFile_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=270
  _STATUS._serialized_end=333
  _PARSECADREQUEST._serialized_start=28
  _PARSECADREQUEST._serialized_end=115
  _PARSECADRESULT._serialized_start=117
  _PARSECADRESULT._serialized_end=203
  _METADATA._serialized_start=205
  _METADATA._serialized_end=243
  _FILE._serialized_start=245
  _FILE._serialized_end=268
  _CADPARSER._serialized_start=335
  _CADPARSER._serialized_end=419
# @@protoc_insertion_point(module_scope)
